name: sb_invoice_app
description: Android app to generate GST invoice PDFs with auto-calculation and auto numbering.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.7
  printing: ^5.12.0
  intl: ^0.19.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  downloads_path_provider_28: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true